### ISSUE TITLE
Can't connect pan gesture to ViewController

### ISSUE THREAD

**Issue by westminsterabi** [uchicago-mobi/MPCS51030-2019-Spring-Forum#30] opened 2019-04-30 18:00 UTC
I'm trying to drag and drop the pan gesture recognizer onto my X and O pieces and when I do so, they show up under the view controller scene. However, when I try to control-drag them to the ViewController class it will first allow me to do so (for some reason the object is always Exit) and then *not* connect the outlet. I can't manually add it either. I've looked at the slides and like 3 online tutorials and I can't figure out what I'm doing wrong.

**Comment by hbennett766** [comment] 2019-04-30 18:14
To hook up a pan gesture recognizer to a game piece, all you need to do is drag and drop it onto the piece. To verify this worked, you can check the outlet in the Connections Inspector. The game piece connection inspector will show a gesture recognizer in the outlet collection. The gesture recognizer will show a gesture recognizer referencing outlet.

To provide a reference in code, you drag and connect as you would any other storyboard element. Because it's not giving you the option to make that connection, it sounds like your view controller in the storyboard isn't hooked up properly to the view controller in code.

In the Identity Inspector for your storyboard view controller, did you set its custom class as the view controller class you have in code, e.g. `GameViewController` instead of a generic `UIViewController`?

**Comment by westminsterabi** [comment] 2019-04-30 22:22
You were totally right, but now I'm getting the same thing for my InfoView when I try to add the button in. I double checked to make sure that I set the custom class and it's still not letting me insert the outlet.

**Comment by westminsterabi** [comment] 2019-04-30 22:27
Never mind, I had it as a subview of GridView, instead of ViewController

**Comment by westminsterabi** [comment] 2019-04-30 22:57
Okay still confused actually. When I make it a subview of the view controller it shows up externally to the other view controller and I can manipulate the outlets. Unfortunately, since it has no X or Y coordinates it doesn't show up when I press the info button. If I put it as a subview of GridView it DOES show up but the outlets don't work anymore.

**Comment by westminsterabi** [comment] 2019-04-30 23:27
Ugh ok so both the outlets are working but I can't animate twice for some reason, just the one time.

**Comment by hbennett766** [comment] 2019-04-30 23:38
Can you clarify what’s not working? What outlets are you referring to with “both outlets”, and what will only animate once?

**Comment by westminsterabi** [comment] 2019-04-30 23:45
Sure, sorry. Basically it seems like individually the button on the modal to close it, and the info button both work. However, when I try to bring it in from above the view and dismiss it, it will come in and never go away. I know that the dismissal button works on its own though, because when I start the modal into the middle of the view and dismiss it it works fine. It's just using them in succession that seems to cause a problem. Maybe I'm wrong though. My code is all pushed.

**Comment by hbennett766** [comment] 2019-05-01 00:51
The code inside your animation is currently `self.transform = CGAffineTransform(translationX: 0, y: 500)`. What that's doing is just creating an instance of a transform and assigning it to `self`. Instead, you should be calling the method that actually does the transformation.

Check out the final paragraph of the "Overview" section in the [CGAffineTransform docs](https://developer.apple.com/documentation/coregraphics/cgaffinetransform) for a great explanation, and also for the method you should be calling.

**Comment by westminsterabi** [comment] 2019-05-01 02:46
I don't understand what's going on [here](http://uchicago.mobi/ios-development/sessions/session4/assets/Lecture-4.pdf) at slide 40 then. Sorry, I think I must be missing something!

**Comment by hbennett766** [comment] 2019-05-01 02:50
Hmmm yeah me too, maybe this has some way of working that I don’t know about.  @chelseatroy you know what’s up with this?

**Comment by chelseatroy** [comment] 2019-05-01 05:14
Hi folks!

I pulled down your code, Abi, and I want to make sure I understand what's up. It sounds like previously the infoView animations (drop into view upon clicking the info button and drop out of view upon clicking the OK button) weren't working in succession.

I just pulled down your code on my machine, and your info button's animations do appear to be working in succession for me. Please let me know if I'm missing what the issue is!

**Comment by hbennett766** [comment] 2019-05-01 12:55
The way of doing the animation in slide 40 (abi linked it above) wasn’t working for her (or me). Wondering if we were missing something

**Comment by westminsterabi** [comment] 2019-05-01 15:43
@chelseatroy I had to add Hannah's suggestion, and I got it to work. Was there another way we were supposed to do it?

**Comment by chelseatroy** [comment] 2019-05-01 15:57
Hi folks!

I am happy with Hannah's suggestion. She is right—as is the slide. 

So on slide 40 we do a rotation animation by instantiating a `CGAffineTransform`:

<img width="1236" alt="Screen Shot 2019-05-01 at 10 43 55 AM" src="https://user-images.githubusercontent.com/5744164/57026551-b9d3aa80-6bff-11e9-9bd7-92575ea2d378.png">

This works...for _rotation_. Not for translation. 

When I put the following code into `ViewMagicGuide`...

<img width="1125" alt="Screen Shot 2019-05-01 at 10 46 06 AM" src="https://user-images.githubusercontent.com/5744164/57026594-ceb03e00-6bff-11e9-988c-9b24243a9df6.png">

and I press the "animate" button...

<img width="371" alt="Screen Shot 2019-05-01 at 10 45 57 AM" src="https://user-images.githubusercontent.com/5744164/57026616-d53eb580-6bff-11e9-807b-6d9f51752e61.png">

The view rotates, but it does not slide downward by 300 points. 

Update forthcoming on the reason for this. In the meantime, feel free to move forward!

**Closed as completed** 2019-05-04 22:56 UTC
Labels: assignment-4
